* transcript
** Greg: We have a few things to figure out.
These 3DOF controllers are in a couple categories:
- Ones that have a trigger
- Ones that don't have a trigger
And a third category, if you like:
- Magic leap has a trigger and a non-depressable touchpad.
*** utterance : https://www.jonicoma.com/ux_design_mtg/utterances/greg-we_have_a_few_things_to_figure_out.mp4
*** raw : https://www.jonicoma.com/ux_design_mtg/utterances/john_perspective_raw.mp4
** 
* rest
 
Dom : Oh my god, are you serious?

Greg : Yes

Dom : Does it have a trigger though?

John : You can still click it.

Kevin : Nonono it's still clickable.

John : It's just not depressing.

Kevin : Yea. It's tapped.

John : It knows when you tap it. It's not ...

Dom : It knows when you tap it or when you press it? That's different.

Greg : Yea. There's one less degree of freedom though right because 
you have all of those on the Oculus Go controller but you're missing 
one now on the Magic Leap.

Kevin : Uh, without knowing the API, it could be pressure-sensitive.
So like, it can differentiate that.
If it's the way I expect it to be, it's like iOS, where you have haptic 
push and press. Like it knows the difference between a press and a tap.

